// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZbYfYOAZopTIFNF2iBo4uBNoKo8RdMQ',
    appId: '1:295949738095:web:410a113bf60b3aee1ead9a',
    messagingSenderId: '295949738095',
    projectId: 'stackfood-4d9d4',
    authDomain: 'stackfood-4d9d4.firebaseapp.com',
    storageBucket: 'stackfood-4d9d4.appspot.com',
    measurementId: 'G-0605PD5LZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-nA5RFqMIQu4vmo0xQMkFAegChQ54gs',
    appId: '1:295949738095:android:fbf8ad556daf21c81ead9a',
    messagingSenderId: '295949738095',
    projectId: 'stackfood-4d9d4',
    storageBucket: 'stackfood-4d9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvOFA_IZUqH7kCSQGvq5woOwWAd1XWgqE',
    appId: '1:295949738095:ios:e23e6f1f7a28162e1ead9a',
    messagingSenderId: '295949738095',
    projectId: 'stackfood-4d9d4',
    storageBucket: 'stackfood-4d9d4.appspot.com',
    iosClientId: '295949738095-hu5aijgjjta6mem4h6jr8n8t019327id.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.stackFood',
  );
}
